[executer.cpp]
command = "g++ main.cpp -o main && main"

[executer.py]
repl = true
prompt = ">>> "
command = "python -iqu"

[executer.js]
repl = true
prompt = ["> ", "... "]
command = "node -e \"require('repl').start({ignoreUndefined: true})\""

[executer.c]
command = "gcc main.c -o main && main"

[executer.r]
repl = true
prompt = ""
command = "R -q --no-save --no-echo"
output-transform = "re.sub('^\\[\\d+\\]\\s?', '', output)"

[executer.rs]
command = "rustc main.rs && main"

[executer.bash]
repl = true
prompt = ""
command = "bash"
